language: java
sudo: false
addons:
  hosts:
  - db
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
- docker
install:
- docker build -t database db/.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mvn clean
jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.AppTest
  - stage: integration tests
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.AppIntegrationTest
  - stage: GitHub Release
    install: skip
    jdk: oraclejdk11
    script:
    - echo "Deploying to GitHub Releases"
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    before_deploy:
    - git config --local user.name "Christopher Wales"
    - git config --local user.email "chriswales95@outlook.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      file: "$TRAVIS_BUILD_DIR/target/seMethods.jar"
      skip_cleanup: true
  - stage: Google Cloud Deploy
    install: skip
    jdk: oraclejdk11
    before_script:
    - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com
      | bash > /dev/null; fi
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components install kubectl
    - gcloud version
    - gcloud auth activate-service-account --key-file client-secret.json
    script:
    - gcloud config set project semethods-235110
    - gcloud config set compute/zone europe-west2-b
    - export PROJECT_ID="$(gcloud config get-value project -q)"
    - gcloud auth configure-docker
    - docker build -t gcr.io/${PROJECT_ID}/db db/.
    - docker push gcr.io/${PROJECT_ID}/db
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    - docker build -t gcr.io/${PROJECT_ID}/app .
    - docker push gcr.io/${PROJECT_ID}/app
    - docker build -t gcr.io/${PROJECT_ID}/web web/.
    - docker push gcr.io/${PROJECT_ID}/web
    - gcloud container clusters create hr-cluster --num-nodes=1
    - kubectl run db --image=gcr.io/${PROJECT_ID}/db --port 3306
    - kubectl expose deployment db --name=db
    - kubectl run app --image=gcr.io/${PROJECT_ID}/app --port 8080
    - kubectl expose deployment app --name=app
    - kubectl run web --image=gcr.io/${PROJECT_ID}/web --port 80
    - kubectl expose deployment web --port=80 --target-port=80 --type=LoadBalancer
stages:
- unit tests
- integration tests
- name: GitHub Release
  if: branch = master
- name: Google Cloud Deploy
  if: branch = master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_9e2cf18823ef_key -iv $encrypted_9e2cf18823ef_iv
  -in client-secret.json.enc -out client-secret.json -d
